/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KTBX9sOOOL4
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { JSX, SVGProps } from "react"

export function SalesChatbot() {
  return (
    <div key="1" className="flex h-screen">
      <div className="flex-1" />
      <div className="w-[400px] p-4 space-y-4 bg-white border-l">
        <div className="flex justify-between">
          <h2 className="text-xl font-semibold">Chat</h2>
          <Button className="text-gray-500" variant="ghost">
            Cart
          </Button>
        </div>
        <div className="flex flex-col space-y-2">
          <div className="flex items-end justify-start">
            <div className="max-w-xs rounded-lg bg-gray-100 p-3">
              <p className="text-sm">Need car rental from san jose airport in costa rica on feb 3 - 5</p>
            </div>
          </div>
          <div className="flex items-start justify-end">
            <div className="max-w-xs rounded-lg bg-blue-100 p-3">
              <p className="text-sm">How about a compact car from XYZ Rentals for $45/day?</p>
              <Button className="mt-2">Add to cart</Button>
            </div>
          </div>
        </div>
        <div className="flex items-center p-2 bg-gray-200 rounded-full mt-auto absolute bottom-0 w-full max-w-[400px]">
          <Input className="flex-1 bg-transparent" placeholder="Message KAYAK - Flights, Hotels & Cars..." />
          <SendIcon className="w-6 h-6 text-gray-500" />
        </div>
      </div>
    </div>
  )
}


function SendIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
